project:
  type: website

brand: _brand.yml

format:
  html:
    toc: true
    theme:
      - default
      - tlm-theme.scss
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://use.typekit.net/tag1lvz.css">
